### ISSUE TITLE
Docker image reporting errors

### ISSUE THREAD

**Issue by blurry-cat** [carbonsilicon-ai/CarsiDock#3]
I've tried many times to install it with the same error. So I would like to ask what is the reason and how to fix it? I think it's probably the error in this step: make install-python-package

#######

DockerFile:28
--------------------
  27 |     COPY ./dockcpp /app/dockcpp
  28 | >>> RUN cd /app/dockcpp && mkdir build && cd build && \
  29 | >>>         cmake .. && make install-python-package && \
  30 | >>>         cd ../../
  31 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /app/dockcpp && mkdir build && cd build &&         cmake .. && make install-python-package &&         cd ../../" did not complete successfully: exit code: 2

**Comment by Le-Phung-Hien** [comment]
Hi, I also had the same error. Using the previous version of the dockerfile solved the problem.

**Comment by blurry-cat** [comment]
> Hi, I also had the same error. Using the previous version of the dockerfile solved the problem.

Hi Le, Thank you very much for your attention and reply!
I'm not familiar with Github, where do you find the previous version of the dockerfile? Or can you just paste it and provide it, thanks!

**Comment by gitabtion** [comment]
@blurry-cat Hi, here is the previous vesion of dockerfile:
```dockerfile
# https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-04.html
FROM nvcr.io/nvidia/pytorch:22.04-py3

RUN conda install -y -c openbabel openbabel
RUN conda install -y -c dglteam dgl-cuda11.6
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY ./lib/pydock-0.4-cp38-cp38-manylinux_2_31_x86_64.whl /app/pydock-0.4-cp38-cp38-manylinux_2_31_x86_64.whl
RUN pip install /app/pydock-0.4-cp38-cp38-manylinux_2_31_x86_64.whl
```
 or you can use image in docker hub by changing `carsidock:v1` to `abtion/carsidock:v2` in command:
`docker run -v ./:/Docking --gpus all abtion/carsidock:v2 python /Docking/run_core_set_eval.py --cuda_convert`

**Comment by blurry-cat** [comment]
@gitabtion Hi, thanks for your help, now the software is installed!

But I still have some questions about how to use it: 
1. I don't quite understand whether the ①# redocking and ②# docking for decoys in the #Docking step are related to the subsequent #Screening step;
2. If I download a protein molecule (from the PDB), which already contains its ligand, can I do the Screening step directly? Do I need to remove the ligand structure from the protein before Screening? 

Waiting for your reply.

**Comment by gitabtion** [comment]
> @gitabtion Hi, thanks for your help, now the software is installed!
> 
> But I still have some questions about how to use it:
> 
> 1. I don't quite understand whether the ①# redocking and ②# docking for decoys in the #Docking step are related to the subsequent #Screening step;
> 2. If I download a protein molecule (from the PDB), which already contains its ligand, can I do the Screening step directly? Do I need to remove the ligand structure from the protein before Screening?
> 
> Waiting for your reply.

@blurry-cat Hi, thanks for your attention.

1. CarsiDock contains 2 modules: docking and scoring. 
   - The docking step (redocking and docking for decoys) only outputs conformers and docking socre (for sorting the conformers). The docking script `run_docking_inference.py` only contains docking module.
   - The scoring step use rtms to scoring the conformers for screening. The screening script `run_screening.py` contains the whole process of docking and scoring. The docking results in the above two scripts are the same.
2. We usually separate the protein and ligand before using CarsiDock.

**Comment by blurry-cat** [comment]
@gitabtion Hi，thanks again!

Your response addresses the issues I raised. But there are a few more I would like to ask:
①How do I choose the input for the parameter --reflig for protein molecules without a ligand reference (i.e. protein-ligand co-crystallization on the PDB)? 
② I tested the Docking step and it outputs 25 conformers by default, is it possible to output only the first conformer after sorting?

Sincerely

**Comment by gitabtion** [comment]
> @gitabtion Hi，thanks again!
> 
> Your response addresses the issues I raised. But there are a few more I would like to ask: ①How do I choose the input for the parameter --reflig for protein molecules without a ligand reference (i.e. protein-ligand co-crystallization on the PDB)? ② I tested the Docking step and it outputs 25 conformers by default, is it possible to output only the first conformer after sorting?
> 
> Sincerely

@blurry-cat Hi, 
1. CarsiDock is a semi-flexible docking algorithm that requires reflig to cut pockets, and works best when using ligand in the complex crystal as reflig.
2. Output only the first conformation is not supported yet, you can add a post script for further processing

**Comment by Grayzyys** [comment]
> [@blurry-cat](https://github.com/blurry-cat) Hi, here is the previous vesion of dockerfile:
> 
> # https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-04.html
> FROM nvcr.io/nvidia/pytorch:22.04-py3
> 
> RUN conda install -y -c openbabel openbabel
> RUN conda install -y -c dglteam dgl-cuda11.6
> RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
> COPY ./requirements.txt /app/requirements.txt
> RUN pip install -r /app/requirements.txt
> 
> COPY ./lib/pydock-0.4-cp38-cp38-manylinux_2_31_x86_64.whl /app/pydock-0.4-cp38-cp38-manylinux_2_31_x86_64.whl
> RUN pip install /app/pydock-0.4-cp38-cp38-manylinux_2_31_x86_64.whl
> or you can use image in docker hub by changing `carsidock:v1` to `abtion/carsidock:v2` in command: `docker run -v ./:/Docking --gpus all abtion/carsidock:v2 python /Docking/run_core_set_eval.py --cuda_convert`

Hi，I also have tried many times to install it with this error . From above answer , I only modify the code from "nvcr.io/nvidia/pytorch:22.09-py3" to"nvcr.io/nvidia/pytorch:22.04-py3" , and"RUN pip install  dgl -f https://data.dgl.ai/wheels/cu118/repo.html" to "RUN pip install  dgl -f https://data.dgl.ai/wheels/cu116/repo.html" in the original Dockerfile . Should I use previous dockerfile above to replace all the code in the original dockerfile ? I would appreciate it if you could help me fix it . I intercept the error in this step: 
 > [ 2/11] RUN pip install  dgl -f https://data.dgl.ai/wheels/cu116/repo.html:
2177.5     for chunk in response.raw.stream(
2177.5   File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
2177.5     data = self.read(amt=amt, decode_content=decode_content)
2177.5   File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
2177.5     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
2177.5   File "/opt/conda/lib/python3.8/contextlib.py", line 131, in __exit__
2177.5     self.gen.throw(type, value, traceback)
2177.5   File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
2177.5     raise ReadTimeoutError(self._pool, None, "Read timed out.")
2177.5 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
------
Dockerfile:18
--------------------
  16 |     
  17 |     # Install Python Requirements
  18 | >>> RUN pip install  dgl -f https://data.dgl.ai/wheels/cu116/repo.html
  19 |     # RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
  20 |     COPY ./requirements.txt /app/requirements.txt
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install  dgl -f https://data.dgl.ai/wheels/cu116/repo.html" did not complete successfully: exit code: 2
