### ISSUE TITLE
Shared Memory Shortage Issue and Unidentified Additional File Generation While Using CarsiDock

### ISSUE THREAD

**Issue by ORCAaAaA-ui** [carbonsilicon-ai/CarsiDock#4]
Hello,

I've encountered several issues while conducting screening tests on SDF decoys using the CarsiDock model. Below is a summary of the command executed and the error messages that arose.

**Command Executed:**

docker run -v ./:/Docking --gpus all carsidock:v1 python /Docking/run_screening.py --pdb_file example_data/ace_p.pdb --reflig example_data/ace_l.sdf --ligands example_data/ace_decoys.sdf --output_dir outputs/ace --cuda_convert

**Key Error Messages:**

DGLWarning: Recommend creating graphs by dgl.graph(data) instead of dgl.DGLGraph(data).
Multiple instances of ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
RuntimeError: DataLoader worker (pid 117146) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.
Subsequent RuntimeErrors indicating inability to write to file due to "No space left on device."
These errors seem to point towards insufficient shared memory available for the workers, ultimately causing the DataLoader workers to exit unexpectedly. Despite these issues, docking poses for each decoy molecule were successfully generated. However, in addition to the expected decoy molecules, 56 additional docking pose files were generated with names like "AHMWJENOOQHUPF-OWOJBTEDSA-N."

**I'm curious about two main points:**

1. What might be the cause of the shared memory shortage and the "Unexpected bus error," and how can these issues be effectively resolved?

2. The origin and significance of the additional 56 docking pose files named with unique identifiers – what do these files represent?

I've followed the setup instructions carefully and ensured that my system meets the recommended specifications. It would be great to get some insights into these issues, as I am unsure how to proceed with troubleshooting.

I will add the full error message file. 
[full_error_message.txt](https://github.com/carbonsilicon-ai/CarsiDock/files/15032555/full_error_message.txt)

Thank you in advance for any help or guidance provided.

(The server specifications are CPU: AMD Ryzen Threadripper 7960X 24-Cores, GPU: Nvidia RTX 4090, and there were absolutely no memory issues while performing calculations through the model. I confirmed this through htop and nvidia-smi.)

**Comment by gitabtion** [comment]
Thans for your attention! 
1. docker default shm size maybe not enough for RTMScore module, try raise it by:
```shell
docker --shm-size 8g run -v ./:/Docking --gpus all carsidock:v1 python /Docking/run_screening.py --pdb_file example_data/ace_p.pdb --reflig example_data/ace_l.sdf --ligands example_data/ace_decoys.sdf --output_dir outputs/ace --cuda_convert
```
2. These files are the docking results of carsidock, and the docking pose in each file are sorted by docking score, we recommend using the first one for virtual screening.
