### ISSUE TITLE
 Inconsistent Scoring Data between SDF Files and score.dat in DEKOIS Benchmark Screening

### ISSUE THREAD

**Issue by ORCAaAaA-ui** [carbonsilicon-ai/CarsiDock#7]
**Description**
I have been using the run_screening.py script for screening compounds within the DEKOIS benchmark set. Upon examining the results, I encountered a significant discrepancy in the score values reported in different parts of the output:

- SDF Output Files: The "score" property values within each SDF file range from 2 to 3.
- score.dat File: The score values listed here range from 10 to 40.

Additionally, I observed that even when a molecule's binding pose receives a high score, it appears to still exhibit quite a few steric clashes with the protein's residues.

**Queries**

1. Could someone clarify which set of scores reflects the accurate results of the screening? This inconsistency is crucial for my analysis, and understanding the correct scoring is essential for further steps in my research.
2. Is it typical for the highest-scoring compounds in such benchmarks to exhibit clashes with the protein? Understanding whether this is a common occurrence or an anomaly is crucial for interpreting the screening results accurately.

Any answers or insights would be greatly appreciated.

Thank you!

**Comment by gitabtion** [comment]
Hi, thanks for your attention!
1. Please use score values from score.dat for screening.
2. Some conformer clashes with protein is one of limitations of AI Docking methods, include CarsiDock, However, this does not affect the effectiveness of virtual screening.
