### ISSUE TITLE
run_screening.py Script Fails with "IndexError: list index out of range" on Certain DEKOIS Targets

### ISSUE THREAD

**Issue by ORCAaAaA-ui** [carbonsilicon-ai/CarsiDock#8]
**Description**
While screening the DEKOIS set with the run_screening.py script, I encountered a recurring error that causes the screening to stop prematurely on approximately 15 target proteins. The error is as follows:

```
Traceback (most recent call last):
  File "/work/run_screening_origin.py", line 106, in <module>
    main(args)
  File "/work/run_screening_origin.py", line 79, in main
    docked_mol.append(outputs['mol_list'][0])
IndexError: list index out of range
```

**Request for Assistance**
I have reviewed the input molecules and found no apparent issues. Re-running the screenings for these specific target proteins consistently yields the same error. Could someone provide insights into what might be causing this IndexError? It seems that the outputs['mol_list'] might be empty, but I'm unsure why this would occur, especially since the inputs appear to be correct. 

Any advice on how to resolve or debug this issue would be greatly appreciated.

Thank you!

**Comment by gitabtion** [comment]
Hi, there will be some ligands that fail in docking. They can be skipped.
