### ISSUE TITLE
Run failed to compute RMSD. Very little info to debug.

### ISSUE THREAD

**Issue by agarrubio** [carbonsilicon-ai/CarsiDock#9]
The test command works:
```
docker run --gpus all --shm-size=2g  -v /home/alejandro/CarsiDock:/Docking carsidock:v1 python /Docking/run_docking_inference.py --pdb_file example_data/4YKQ_hsp90_40_water.pdb --sdf_file example_data/4YKQ_hsp90_40.sdf --cuda_convert
```
But my command fails:
```
docker run --gpus all --shm-size=2g  -v /home/alejandro/CarsiDock:/Docking carsidock:v1 python /Docking/run_docking_inference.py --pdb_file input/rec7_4.pdb --sdf_file input/rec7_4.sdf --cuda_convert
```
The only output is:
```
@> 2886 atoms and 1 coordinate set(s) were parsed in 0.02s.
read data...
docking...0
fail to compute rmsd
rmsd: None
```
Both my pdb and sdf work well with gnina and DiffDock.
These are here `https://drive.google.com/drive/folders/1AOjhhStJ_QN8U5aGyi-i0bfwRaKpfJiN?usp=drive_link`

Can you help me to debug this? Many thanks!

**Comment by gitabtion** [comment]
It means the docking has failed. Like custom docking methods, there are a few cases of docking failures in CarsiDock. Currently, there is no solution available, but based on our analysis, the ligands that fail to dock have a low probability of being active.

**Comment by agarrubio** [comment]
Many thanks!
